version: "3.2"
services:
  cms:
    build:
      context: './cms/'
      args:
        PHP_VERSION: ${PHP_VERSION}
        APACHE_VERSION: ${APACHE_VERSION}
    ports:
      - "8083:8083"
      - "3306:3306"
    container_name: cms-api
    network_mode: "host"
volumes:
  data:
